name: chocolatine

env:
  MIRROR_URL: https://github.com/EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-suleman.maqsood
  EXECUTABLES: libmy.a
  
on:
  push:
    branches:
    - '!ga-ignore-*'
  pull_request:
    branches:
    - '*'

  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Compile code
        run: |
          make
      - name: run programme
        run: |
          ./mysh
      - name: Push
        run: |
          echo " Succes Compile "
    if: ${{ job.status == 'success' }}
    
  job2:
      needs: job1
      runs-on: ubuntu-latest
      
      steps:
        - name: coding-style-check
          run : coding-style.sh . .
